/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    SvgComponent: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"404" | "bug" | "build" | "button" | "cascader" | "chart" | "checkbox" | "clipboard" | "code" | "color" | "component" | "dashboard" | "date-range" | "date" | "dict" | "documentation" | "download" | "drag" | "druid" | "edit" | "education" | "email" | "example" | "excel" | "exit-fullscreen" | "eye-open" | "eye" | "form" | "fullscreen" | "github" | "guide" | "icon" | "input" | "international" | "job" | "language" | "link" | "list" | "lock" | "log" | "logininfor" | "message" | "money" | "monitor" | "nested" | "number" | "online" | "password" | "pdf" | "people" | "peoples" | "phone" | "post" | "qq" | "question" | "radio" | "rate" | "redis-list" | "redis" | "row" | "search" | "select" | "server" | "shopping" | "size" | "skill" | "slider" | "star" | "swagger" | "switch" | "system" | "tab" | "table" | "textarea" | "theme" | "time-range" | "time" | "tool" | "tree-table" | "tree" | "upload" | "user" | "validCode" | "wechat" | "zip">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"404" | "bug" | "build" | "button" | "cascader" | "chart" | "checkbox" | "clipboard" | "code" | "color" | "component" | "dashboard" | "date-range" | "date" | "dict" | "documentation" | "download" | "drag" | "druid" | "edit" | "education" | "email" | "example" | "excel" | "exit-fullscreen" | "eye-open" | "eye" | "form" | "fullscreen" | "github" | "guide" | "icon" | "input" | "international" | "job" | "language" | "link" | "list" | "lock" | "log" | "logininfor" | "message" | "money" | "monitor" | "nested" | "number" | "online" | "password" | "pdf" | "people" | "peoples" | "phone" | "post" | "qq" | "question" | "radio" | "rate" | "redis-list" | "redis" | "row" | "search" | "select" | "server" | "shopping" | "size" | "skill" | "slider" | "star" | "swagger" | "switch" | "system" | "tab" | "table" | "textarea" | "theme" | "time-range" | "time" | "tool" | "tree-table" | "tree" | "upload" | "user" | "validCode" | "wechat" | "zip">;
            default: string;
            required: true;
        };
    }>>, {
        name: "404" | "bug" | "build" | "button" | "cascader" | "chart" | "checkbox" | "clipboard" | "code" | "color" | "component" | "dashboard" | "date-range" | "date" | "dict" | "documentation" | "download" | "drag" | "druid" | "edit" | "education" | "email" | "example" | "excel" | "exit-fullscreen" | "eye-open" | "eye" | "form" | "fullscreen" | "github" | "guide" | "icon" | "input" | "international" | "job" | "language" | "link" | "list" | "lock" | "log" | "logininfor" | "message" | "money" | "monitor" | "nested" | "number" | "online" | "password" | "pdf" | "people" | "peoples" | "phone" | "post" | "qq" | "question" | "radio" | "rate" | "redis-list" | "redis" | "row" | "search" | "select" | "server" | "shopping" | "size" | "skill" | "slider" | "star" | "swagger" | "switch" | "system" | "tab" | "table" | "textarea" | "theme" | "time-range" | "time" | "tool" | "tree-table" | "tree" | "upload" | "user" | "validCode" | "wechat" | "zip";
    }>;
  }
}
